In [2]:
import numpy as np

Задача 1  - Выполнить операции над матрицами

In [3]:
A = np.matrix([[1, 2, 1],
               [-2, 1, 1]])

In [4]:
B = np.matrix([[3, 1],
                [-1, 0],
                [2, 4]])

In [5]:
C = np.matrix([[-2, 2],
                [1, -1],
                [1, 2]])

In [6]:
A2B = A + 2 * np.transpose(B)
A2B

matrix([[7, 0, 5],
        [0, 1, 9]])

In [7]:
B2C = B + 2 * C
B2C

matrix([[-1,  5],
        [ 1, -2],
        [ 4,  8]])

Задача 2 - Создать матрицу размером 8х8 элементов,состоящую из нулей.Заполнить эту матрицу значениями,расположенными в шахматном порядке

In [8]:
Z = np.zeros((8,8))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Задача 3

1. Сформировать два вектора: первый длиной 15 элементов со значениями от 0 до 1,4 с шагом 0,1; второй – длиной 6 элементов со значениями от 1 до 6

In [16]:
v1 = np.arange(0,1.5,0.1)
v2 = np.arange(1,7,1)
print(v1)
print(v2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[1 2 3 4 5 6]


2. Преобразовать первый вектор в матрицу 5х3, а второй – в матрицу 3х2. Выполнить перемножение этих матриц. Сами матрицы и результат их перемножения вывести на экран

In [17]:
m1 = v1.reshape(5,3)
m2 = v2.reshape(3,2)
print(m1)
print(m2)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
M_0 = np.dot(m1, m2)
M_0

array([[ 1.3,  1.6],
       [ 4. ,  5.2],
       [ 6.7,  8.8],
       [ 9.4, 12.4],
       [12.1, 16. ]])

Задача 4



1.   Сформировать вектор из целых чисел (тип элементов должен быть int32) размерностью 36 и значениями 1, 3, 5, 7,... и так далее







In [27]:
v3 = np.arange(1, 73, 2, dtype=np.int32)
print(v3)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]


2. Выделить из этого вектора все элементы со значениями кратными 3. Вывести результат на экран (исходный вектор и с кратными числами)

In [30]:
v4 = v3[v3 % 3 == 0]
print(v3)
print(v4)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
[ 3  9 15 21 27 33 39 45 51 57 63 69]
